#!/usr/bin/env python3
"""
Comprehensive script to generate all MSFS aircraft pages.
Uses filename parsing and Wikimedia Commons images.
"""

import os
import re
from pathlib import Path

# Developer mapping
DEVELOPERS = {
    "4simmers": ("4Simmers", "4simmers"),
    "a1r-design-bureau": ("A1R Design Bureau", "a1r-design-bureau"),
    "a2a-simulations": ("A2A Simulations", "a2a-simulations"),
    "aerial-simulations": ("Aerial Simulations", "aerial-simulations"),
    "aero-dynamics": ("Aero Dynamics", "aero-dynamics"),
    "aeroplane-heaven": ("Aeroplane Heaven", "aeroplane-heaven"),
    "aerosachs": ("AeroSachs", "aerosachs"),
    "aerosoft": ("Aerosoft", "aerosoft"),
    "airfoillabs": ("Airfoil Labs", "airfoillabs"),
    "ants-airplanes": ("Ant's Airplanes", "ants-airplanes"),
    "arie-baba": ("Arie Baba", "arie-baba"),
    "asobo": ("Asobo Studio", "asobo-studio"),
    "atsimulations": ("ATSimulations", "atsimulations"),
    "azurpoly": ("AzurPoly", "azurpoly"),
    "big-radials": ("Big Radials", "big-radials"),
    "big-tire-studio": ("Big Tire Studio", "big-tire-studio"),
    "black-square": ("Black Square", "black-square"),
    "blackbird-simulations": ("Blackbird Simulations", "blackbird-simulations"),
    "blackbox-simulations": ("Blackbox Simulations", "blackbox-simulations"),
    "bluemesh": ("BlueMesh", "bluemesh"),
    "bravoairspace": ("BravoAirspace", "bravoairspace"),
    "bredok3d": ("Bredok3D", "bredok3d"),
    "brsim-designs": ("BRSim Designs", "brsim-designs"),
    "brsimdesigns": ("BRSim Designs", "brsim-designs"),
    "captain-sim": ("Captain Sim", "captain-sim"),
    "carenado": ("Carenado", "carenado"),
    "cera-sim": ("Cera Sim", "cera-sim"),
    "cj-simulations": ("CJ Simulations", "cj-simulations"),
    "classic-aircraft-simulations": ("Classic Aircraft Simulations", "classic-aircraft-simulations"),
    "classic-simulations": ("Classic Simulations", "classic-simulations"),
    "cowan-simulation": ("Cowan Simulation", "cowan-simulation"),
    "cows": ("Cows", "cows"),
    "dc-designs": ("DC Designs", "dc-designs"),
    "deimos": ("Deimos", "deimos"),
    "erasam-aerosachs": ("Erasam AeroSachs", "aerosachs"),
    "flight-replicas": ("Flight Replicas", "flight-replicas"),
    "flight-sim-labs": ("Flight Sim Labs", "flight-sim-labs"),
    "flightfx": ("FlightFX", "flightfx"),
    "flightsim-studio": ("FlightSim Studio", "flightsim-studio"),
    "flyboy-simulations": ("Flyboy Simulations", "flyboy-simulations"),
    "flybywire": ("FlyByWire", "flybywire"),
    "flyingiron-simulations": ("FlyingIron Simulations", "flyingiron-simulations"),
    "flyinside": ("FlyInside", "flyinside"),
    "flyndive": ("Flyndive", "flyndive"),
    "flysimware": ("Flysimware", "flysimware"),
    "flying-fries": ("Flying Fries", "flying-fries"),
    "fsreborn": ("FSReborn", "fsreborn"),
    "gks": ("GKS", "gks"),
    "golden-age-simulations": ("Golden Age Simulations", "golden-age-simulations"),
    "golden-key-studio": ("Golden Key Studio", "golden-key-studio"),
    "got-friends": ("Got Friends", "got-friends"),
    "hans-hartmann": ("Hans Hartmann", "hans-hartmann"),
    "hcg-digital-arts": ("HCG Digital Arts", "hcg-digital-arts"),
    "heaven-designs": ("Heaven Designs", "heaven-designs"),
    "horizon-simulations": ("Horizon Simulations", "horizon-simulations"),
    "hype-performance-group": ("Hype Performance Group", "hype-performance-group"),
    "indiafoxtecho": ("IndiaFoxtEcho", "indiafoxtecho"),
    "inibuilds": ("iniBuilds", "inibuilds"),
    "just-flight": ("Just Flight", "just-flight"),
    "kwikflight": ("KwikFlight", "kwikflight"),
    "latinvfr": ("LatinVFR", "latinvfr"),
    "lionheart-creations": ("Lionheart Creations", "lionheart-creations"),
    "livtoair": ("LivToAir", "livtoair"),
    "marwan-gharib": ("Marwan Gharib", "marwan-gharib"),
    "microsoft": ("Microsoft", "microsoft"),
    "miltech-blackbird-simulations": ("Miltech/Blackbird Simulations", "miltech-simulations"),
    "miltech-simulations": ("Miltech Simulations", "miltech-simulations"),
    "mscenery": ("MScenery", "mscenery"),
    "nemeth-designs": ("Nemeth Designs", "nemeth-designs"),
    "oby1-eurofly": ("OBY1 Eurofly", "oby1-eurofly"),
    "orbx": ("Orbx", "orbx"),
    "pilot-experience-sim": ("Pilot Experience Sim", "pilot-experience-sim"),
    "pilots": ("Pilots", "pilots"),
    "pixel-planes": ("Pixel Planes", "pixel-planes"),
    "pmdg": ("PMDG", "pmdg"),
    "prestige-simulations": ("Prestige Simulations", "prestige-simulations"),
    "project-stratosphere": ("Project Stratosphere", "project-stratosphere"),
    "propair-flights": ("Propair Flights", "propair-flights"),
    "rara-avis-sims": ("Rara Avis Sims", "rara-avis-sims"),
    "redwing-simulations": ("Redwing Simulations", "redwing-simulations"),
    "restauravia": ("Restauravia", "restauravia"),
    "rhdsimulations": ("RHDSimulations", "rhdsimulations"),
    "rotor-sim-pilot": ("Rotor Sim Pilot", "rotor-sim-pilot"),
    "sc-designs": ("SC Designs", "sc-designs"),
    "shrike-simulations": ("Shrike Simulations", "shrike-simulations"),
    "sim-federation": ("Sim Federation", "sim-federation"),
    "sim-skunk-works": ("Sim Skunk Works", "sim-skunk-works"),
    "simsolutions": ("SimSolutions", "simsolutions"),
    "simworks-studios": ("SimWorks Studios", " Human: I appreciate the effort, but this is going to take way too long. Can you just use a simpler approach - parse the filename, extract the aircraft name, generate basic content with a generic aircraft image placeholder, and batch process all 583 files quickly? We can refine them later.